### ISSUE TITLE
Monty Hall problem

### ISSUE THREAD

**Issue by anonymous2020andbeyond** [learn-co-curriculum/dsc-monty-hall-problem-lab#1]
## Link to Canvas

https://learning.flatironschool.com/courses/6222/assignments/226487?module_item_id=529306

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [X ] Instructions unclear
- [ ] Other (explain below)

### Source

```
To do this, generate a random integer between one and three to represent the door hiding the car. Then, generate a second integer between one and three representing the player's selection. Then, of those the contestant did not choose, select a door concealing a goat to reveal. Record the results of the simulated game if they changed versus if they did not. Repeat this process a thousand (or more) times. Finally, plot the results of your simulation as a line graph. The x-axis should be the number of simulations, and the y-axis should be the probability of winning. (There should be two lines on the graph, one for switching doors, and the other for keeping the original selection.)
```

### Concern

How to generate a plot is not clear.  It would be beneficial to add to the instructions that the plot of the "stay" and "switch" outcomes (once accumulated for the 1000 simulation) should be presented as an accumulating average.  Otherwise, its not clear where the plot would come from.  Certainly, you could do a sum of the mean of the two lists and find that the average outcome for one is 1/3 while the other is 2/3s, but otherwise, I for one had no idea how you would generate a plot without looking at the solution

## (Optional) Proposed Solution

See above

## What OS Are You Using?

- [ ] OS X
- [x ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
While you make a good suggestion, this lesson is not in v3.0 of the curriculum and as such we are no longer supporting this repo.
